# Generated by Django 3.0.7 on 2021-09-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_coins', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('remaning_coins', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'coins',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('number_of_tokens', models.IntegerField()),
                ('bidding_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=10)),
                ('is_assigned', models.BooleanField(default=False)),
                ('coin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Coins')),
            ],
            options={
                'db_table': 'bidding_detail',
            },
        ),
    ]
